"""migration

Revision ID: 5fed0fa7d39e
Revises: c9dc6c428193
Create Date: 2024-10-31 14:06:37.743608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fed0fa7d39e'
down_revision: Union[str, None] = 'c9dc6c428193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfps', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_rfps_name'), 'rfps', ['name'], unique=False)
    op.add_column('suppliers', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_column('suppliers', 'name')
    op.drop_index(op.f('ix_rfps_name'), table_name='rfps')
    op.drop_column('rfps', 'name')
    # ### end Alembic commands ###
